# Generated by Django 4.0.5 on 2022-07-01 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(default='READY', max_length=50)),
                ('last_run', models.CharField(default='', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('destination', models.CharField(max_length=1350)),
                ('time', models.TimeField(verbose_name='time to start')),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_q.schedule',),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('path', models.CharField(max_length=750)),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('job', models.ManyToManyField(blank=True, related_name='repositories', to='backup.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(check=models.Q(('monday', False)), name='backup_job_value_matches_type'),
        ),
    ]
