# Generated by Django 4.0.4 on 2022-06-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('last_run', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('destination', models.CharField(max_length=1350)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='time to start')),
                ('MONDAY', models.BooleanField()),
                ('TUESDAY', models.BooleanField()),
                ('WEDNESDAY', models.BooleanField()),
                ('THURSDAY', models.BooleanField()),
                ('FRIDAY', models.BooleanField()),
                ('SATURDAY', models.BooleanField()),
                ('SUNDAY', models.BooleanField()),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backup.job')),
            ],
        ),
        migrations.CreateModel(
            name='Repositories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=750)),
                ('job', models.ManyToManyField(to='backup.job')),
            ],
        ),
    ]
