# Generated by Django 4.0.5 on 2022-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
    ]
