# Generated by Django 4.0.5 on 2022-07-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repsository_path', models.CharField(max_length=810)),
                ('destination_path', models.CharField(max_length=810)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='backup_job_value_matches_type',
        ),
        migrations.AddField(
            model_name='report',
            name='job_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.jobrun'),
        ),
        migrations.AddField(
            model_name='jobrun',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backup.job'),
        ),
    ]
