# Generated by Django 4.0.5 on 2022-07-04 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='job',
            field=models.ForeignKey(default='DELETED', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='backup.job'),
        ),
    ]
