# Generated by Django 4.0.5 on 2022-06-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('backup', '0002_repository_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.schedule'),
        ),
    ]
