# Generated by Django 4.0.5 on 2022-07-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_alter_report_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='report',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='backup.report'),
        ),
    ]
