# Generated by Django 4.0.5 on 2022-07-02 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_alter_track_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.job'),
        ),
        migrations.AlterField(
            model_name='track',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup.report'),
        ),
    ]
