# Generated by Django 4.0.5 on 2022-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_alter_report_job_alter_track_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='Date'),
        ),
    ]
