# Generated by Django 4.0.5 on 2022-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_alter_report_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date'),
        ),
    ]
