# Generated by Django 4.0.5 on 2022-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0006_alter_report_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='modified',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Modified time'),
        ),
    ]
