# Generated by Django 4.0.5 on 2022-07-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0007_alter_report_start_alter_repository_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='destination_path',
        ),
        migrations.AddField(
            model_name='report',
            name='destination_path',
            field=models.CharField(default='xxx', max_length=1350, verbose_name='Destination path'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='start',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(max_length=1350),
        ),
        migrations.AlterField(
            model_name='track',
            name='repsository_path',
            field=models.CharField(max_length=1350),
        ),
    ]
