# Generated by Django 4.0.5 on 2022-07-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0008_remove_track_destination_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='repsository_path',
            new_name='repository_path',
        ),
        migrations.AlterField(
            model_name='track',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backup.report'),
        ),
    ]
